services:
  php:
    build:
      context: ./docker/php
    container_name: hrm_system_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-}
      DATABASE_URL: "mysql://hrm_user:hrm_password@mysql:3306/hrm_system?serverVersion=8.0"
    depends_on:
      - mysql
    networks:
      - hrm_network

  web:
    image: nginx:1.27-alpine
    container_name: hrm_system_web
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - hrm_network

  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: hrm_system_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hrm_system
      MYSQL_USER: hrm_user
      MYSQL_PASSWORD: hrm_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hrm_network

  # Base de datos PostgreSQL (alternativa)
  postgres:
    image: postgres:13
    container_name: hrm_system_postgres
    environment:
      POSTGRES_DB: hrm_system
      POSTGRES_USER: hrm_user
      POSTGRES_PASSWORD: hrm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hrm_network

  # Redis para caché y sesiones
  redis:
    image: redis:7-alpine
    container_name: hrm_system_redis
    ports:
      - "6379:6379"
    networks:
      - hrm_network

  # MailHog para testing de emails
  mailhog:
    image: mailhog/mailhog:latest
    container_name: hrm_system_mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - hrm_network

  # RabbitMQ para mensajería (Event-Driven Architecture)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: hrm_system_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: hrm_user
      RABBITMQ_DEFAULT_PASS: hrm_password
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    networks:
      - hrm_network

  # Elasticsearch para Event Store (opcional)
  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: hrm_system_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - hrm_network

volumes:
  mysql_data:
  postgres_data:
  elasticsearch_data:

networks:
  hrm_network:
    driver: bridge